version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: p@ssword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: mzaretskyy
      MYSQL_PASSWORD: p@ssword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network
  express:
    build: .
    ports:
      - "3000"
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: mzaretskyy
      MYSQL_PASSWORD: p@ssword
      MYSQL_DATABASE: mydatabase
      DB_PORT: 3306
      PORT: 3000
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - .:/usr/src/app
    command: npm run serve
    networks:
      - app_network
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    networks:
      - app_network
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - express
    networks:
      - app_network

volumes:
  mysql_data:
networks:
  app_network:
